{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "cpe_match": [
          {
            "cpe23Uri": "cpe:2.3:a:pysaml2_project:pysaml2:*:*:*:*:*:*:*:*",
            "versionEndIncluding": "4.4.0",
            "vulnerable": true
          }
        ],
        "operator": "OR"
      },
      {
        "cpe_match": [
          {
            "cpe23Uri": "cpe:2.3:o:debian:debian_linux:8.0:*:*:*:*:*:*:*",
            "vulnerable": true
          }
        ],
        "operator": "OR"
      }
    ]
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2016-10149"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "product": {
              "product_data": [
                {
                  "product_name": "pysaml2",
                  "version": {
                    "version_data": [
                      {
                        "version_affected": "\u003c=",
                        "version_value": "4.4.0"
                      }
                    ]
                  }
                }
              ]
            },
            "vendor_name": "pysaml2_project"
          },
          {
            "product": {
              "product_data": [
                {
                  "product_name": "debian_linux",
                  "version": {
                    "version_data": [
                      {
                        "version_affected": "=",
                        "version_value": "8.0"
                      }
                    ]
                  }
                }
              ]
            },
            "vendor_name": "debian"
          }
        ]
      }
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "XML External Entity (XXE) vulnerability in PySAML2 4.4.0 and earlier allows remote attackers to read arbitrary files via a crafted SAML XML request or response."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-611"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "DSA-3759",
          "refsource": "DEBIAN",
          "tags": [
            "Third Party Advisory"
          ],
          "url": "http://www.debian.org/security/2017/dsa-3759"
        },
        {
          "name": "[oss-security] 20170119 Re: CVE request: python-pysaml2 XML external entity attack",
          "refsource": "MLIST",
          "tags": [
            "Mailing List",
            "Patch",
            "Third Party Advisory"
          ],
          "url": "http://www.openwall.com/lists/oss-security/2017/01/19/5"
        },
        {
          "name": "97692",
          "refsource": "BID",
          "tags": [],
          "url": "http://www.securityfocus.com/bid/97692"
        },
        {
          "name": "RHSA-2017:0936",
          "refsource": "REDHAT",
          "tags": [],
          "url": "https://access.redhat.com/errata/RHSA-2017:0936"
        },
        {
          "name": "RHSA-2017:0937",
          "refsource": "REDHAT",
          "tags": [],
          "url": "https://access.redhat.com/errata/RHSA-2017:0937"
        },
        {
          "name": "RHSA-2017:0938",
          "refsource": "REDHAT",
          "tags": [],
          "url": "https://access.redhat.com/errata/RHSA-2017:0938"
        },
        {
          "name": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=850716",
          "refsource": "CONFIRM",
          "tags": [
            "Issue Tracking",
            "Patch",
            "Third Party Advisory"
          ],
          "url": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=850716"
        },
        {
          "name": "https://github.com/rohe/pysaml2/commit/6e09a25d9b4b7aa7a506853210a9a14100b8bc9b",
          "refsource": "CONFIRM",
          "tags": [
            "Issue Tracking",
            "Patch",
            "Third Party Advisory"
          ],
          "url": "https://github.com/rohe/pysaml2/commit/6e09a25d9b4b7aa7a506853210a9a14100b8bc9b"
        },
        {
          "name": "https://github.com/rohe/pysaml2/issues/366",
          "refsource": "MISC",
          "tags": [
            "Issue Tracking",
            "Patch",
            "Third Party Advisory"
          ],
          "url": "https://github.com/rohe/pysaml2/issues/366"
        },
        {
          "name": "https://github.com/rohe/pysaml2/pull/379",
          "refsource": "CONFIRM",
          "tags": [
            "Issue Tracking",
            "Patch",
            "Third Party Advisory"
          ],
          "url": "https://github.com/rohe/pysaml2/pull/379"
        }
      ]
    }
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "accessComplexity": "LOW",
        "accessVector": "NETWORK",
        "authentication": "NONE",
        "availabilityImpact": "NONE",
        "baseScore": 5,
        "confidentialityImpact": "PARTIAL",
        "integrityImpact": "NONE",
        "vectorString": "AV:N/AC:L/Au:N/C:P/I:N/A:N",
        "version": "2.0"
      },
      "exploitabilityScore": 10,
      "impactScore": 2.9,
      "obtainAllPrivilege": false,
      "obtainOtherPrivilege": false,
      "obtainUserPrivilege": false,
      "severity": "MEDIUM",
      "userInteractionRequired": false
    },
    "baseMetricV3": {
      "cvssV3": {
        "attackComplexity": "LOW",
        "attackVector": "NETWORK",
        "availabilityImpact": "NONE",
        "baseScore": 7.5,
        "baseSeverity": "HIGH",
        "confidentialityImpact": "HIGH",
        "integrityImpact": "NONE",
        "privilegesRequired": "NONE",
        "scope": "UNCHANGED",
        "userInteraction": "NONE",
        "vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
        "version": "3.0"
      },
      "exploitabilityScore": 3.9,
      "impactScore": 3.6
    }
  },
  "lastModifiedDate": "2018-01-05T02:30Z",
  "publishedDate": "2017-03-24T14:59Z"
}